import React from "react";
import PropTypes from "prop-types";

function Keyboard({
  getKeyboardValue,
  updateGuessedWord,
  deleteAlphabet,
  shiftButton,
}) {
  return (
    <>
      <div id="KeyboardContainer">
        <div className="KeyboardRow01">
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ภ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ถ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ุ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ึ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ค"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ต"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="จ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ข"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ช"
          ></button>
          <button
            className="Button Del"
            id="Del"
            onClick={deleteAlphabet}
            value="del"
          ></button>
        </div>
        <div className="KeyboardRow02">
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ไ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ำ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="พ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ะ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ั"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ี"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ร"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="น"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ย"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="บ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ล"
          ></button>
        </div>
        <div className="KeyboardRow03">
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ฟ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ห"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ก"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ด"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="เ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="้"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="่"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="า"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ส"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ว"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ง"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ฃ"
          ></button>
        </div>
        <div className="KeyboardRow04">
          <button
            className="Button Shift"
            id="Shift"
            onClick={shiftButton}
            value="&#9750;"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ผ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ป"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="แ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="อ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ิ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ื"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ท"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ม"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ใ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ฝ"
          ></button>
          <button
            className="Button Enter"
            id="Enter"
            onClick={updateGuessedWord}
            value="enter"
          ></button>
        </div>
      </div>
      <div id="KeyboardContainerShift">
        <div className="KeyboardRow01">
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ฎ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ฑ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ธ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ู"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="๊"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ณ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ญ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ฐ"
          ></button>
          <button
            className="Button Del"
            id="Del"
            onClick={deleteAlphabet}
            value="del"
          ></button>
        </div>
        <div className="KeyboardRow02">
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ฤ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ฆ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ฏ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="โ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ฌ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="็"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="๋"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ษ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ศ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ซ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ฅ"
          ></button>
        </div>
        <div className="KeyboardRow03">
          <button
            className="Button Shift"
            id="Shift"
            onClick={shiftButton}
            value="&#9750;"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ฉ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ฮ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="์"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ฒ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ฬ"
          ></button>
          <button
            className="Button"
            onClick={getKeyboardValue}
            value="ฦ"
          ></button>
          <button
            className="Button Enter"
            id="Enter"
            onClick={updateGuessedWord}
            value="enter"
          ></button>
        </div>
      </div>
    </>
  );
}

export default Keyboard;

Keyboard.propTypes = {
  getKeyboardValue: PropTypes.func,
  updateGuessWord: PropTypes.func,
};
